egate/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.main, name='main'),
    path('main', views.main, name='main'),
    path('invitacion', views.crearInvitacion, name='invitacion'),
    path('autorizarproveedor', views.crearAutorizacionProveedor, name='autorizarproveedor'),
    path('todayinvitations', views.todayInvitations, name='todayinvitations'),
    path('timeslotinvitations/<str:timeslot>', views.previousInvitations, name='timeslotinvitations'),
    path('timeslotnextinvitations/<str:timeslot>', views.nextInvitations, name='timeslotnextinvitations'),
    path('invitado/create', views.crearInvitado, name='crearinvitado'),
    path('direccion/create', views.crearDireccion, name='creardireccion'),
    path('ajax/load-dropdownproveedor/', views.cargarProveedores, name='ajax_cargarproveedores'),
    path('changeinvitationstate/<int:mypk>', views.setInvitationState, name='changeinvitationstate'),
]

pwa1/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
	path('egate/', include('egate.urls')),
    path('profile/', include('userprofile.urls')),
    path('admin/', admin.site.urls),
    path('myauth/', include('myauthapp.urls')),
]

urlpatterns += [
    path('', RedirectView.as_view(url='/egate/')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

egate/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
#clase abstracta persona
class Person(models.Model):
	nombres = models.CharField(max_length=60)
	apellidos = models.CharField(max_length=60)
	dob = models.DateField(blank=True,null=True)


	class Meta:
		abstract = True

class Invitado(Person):
	GENERO = (
	('M','Masculino'),
	('F','Femenino'),	
	)

	def cedula_default():
		default_cedula = '0000000000'
		return default_cedula

	cedula= models.CharField(max_length=13,blank=True, default=cedula_default)
	genero = models.CharField(max_length=1,choices=GENERO)
	email = models.EmailField(max_length=60,blank=True,null=True)
	telefono = models.CharField(max_length=16,blank=True,null=True)
	movil = models.CharField(max_length=10,blank=True,null=True)
	pk_user = models.ForeignKey(User,on_delete=models.CASCADE)

	def __str__(self):
		return self.nombres

class Direccion(models.Model):
	manzana = models.CharField(max_length=10)
	villa = models.CharField(max_length=10)
	calle1 = models.CharField(max_length=80,blank=True, null=True)
	calle2 = models.CharField(max_length=80,blank=True, null=True)
	conjunto = models.CharField(max_length=80)
	departamento = models.CharField(max_length=10,blank=True,null=True)
	residente_pk = models.ForeignKey(User, on_delete=models.CASCADE)

	def __str__(self):
		return self.manzana+" - "+self.villa

class Invitacion(models.Model):
	ESTADOS_INVITACION=(
	('Pendiente','P'),
	('Realizado','R'),
	('Cancelado','C'),
	('Vencido','V'),
	)

	TIPO_INVITACION=(
		('S','SOCIAL'),
		('T','TRABAJO'),
		)

	def cedula_default():
		default_cedula = '0000000000'
		return default_cedula

	fecha_emision = models.DateTimeField(auto_now=True)
	fecha_invitacion = models.DateTimeField()
	estado_invitacion = models.CharField(max_length=1,choices=ESTADOS_INVITACION)
	residente_pk = models.ForeignKey(User,on_delete=models.CASCADE)
	nombre_invitado = models.CharField(max_length=60)
	apellido_invitado = models.CharField(max_length=60)
	cedula_invitado = models.CharField(max_length=13, default=cedula_default,blank=True)
	tipo_invitacion = models.CharField(max_length=1,choices=TIPO_INVITACION)
	codigo_invitacion = models.CharField(max_length=128)
	save_contact = models.BooleanField(blank=True)
	direccion_pk = models.ForeignKey(Direccion,on_delete=models.CASCADE)


	def __str__(self):
		return self.nombre_invitado

class CategoriaProveedores(models.Model):
	ESTADO_PROVEEDOR=(
		('A','ACTIVO'),
		('I','INACTIVO'),
		)

	nombres_categoria = models.CharField(max_length=100)
	estado_categoria = models.CharField(max_length=1, choices=ESTADO_PROVEEDOR)

	def __str__(self):
		return self.nombres_categoria

class Proveedores(models.Model):
	ESTADO_PROVEEDOR=(
		('A','ACTIVO'),
		('I','INACTIVO'),
		)

	nombres_proveedor = models.CharField(max_length=100)
	estado_proveedor = models.CharField(max_length=1, choices=ESTADO_PROVEEDOR)
	categoria_pk = models.ForeignKey(CategoriaProveedores, on_delete=models.CASCADE)
	direccion_proveedor = models.CharField(max_length=150,blank=True,null=True)
	georeferencia_proveedor = models.CharField(max_length=200,blank=True,null=True)

	def __str__(self):
		return self.nombres_proveedor

class AutorizarProveedor(models.Model):
	ESTADOS_AUTORIZACION=(
	('Pendiente','P'),
	('Realizado','R'),
	('Cancelado','C'),
	('Vencido','V'),
	)

	fecha_emision = models.DateTimeField(auto_now=True)
	fecha_autorizacion = models.DateTimeField()
	estado_autorizacion = models.CharField(max_length=1,choices=ESTADOS_AUTORIZACION)
	nombre_proveedor = models.ForeignKey(Proveedores,on_delete=models.CASCADE)
	nombres_categoria = models.ForeignKey(CategoriaProveedores, on_delete=models.CASCADE)
	residente_pk = models.ForeignKey(User,on_delete=models.CASCADE)
	codigo_invitacion = models.CharField(max_length=128)
	direccion_pk = models.ForeignKey(Direccion,on_delete=models.CASCADE)

	def __str__(self):
		return self.nombre_proveedor	

egate/forms.py
from datetime import datetime,date
import logging
from django import forms
from django.forms import ModelForm, Form
from .models import Invitacion,Invitado, Direccion, AutorizarProveedor, CategoriaProveedores,Proveedores
from django.core.exceptions import ValidationError
from django.utils import timezone
import pytz


logger = logging.getLogger(__name__)

class AutorizaProveedorForm(ModelForm):
	
	
	class Meta:
		model= AutorizarProveedor
		fields = ['fecha_autorizacion','nombres_categoria','nombre_proveedor','direccion_pk']

	def __init__(self,user,*args,**kwargs):
		
		super(AutorizaProveedorForm,self).__init__(*args,**kwargs)
		self.fields['direccion_pk'].queryset = Direccion.objects.filter(residente_pk=user)
		self.fields['nombre_proveedor'].queryset = Proveedores.objects.none()

		if 'nombres_categoria' in self.data:
			categoriaid = int(self.data.get('nombres_categoria'))
			self.fields['nombre_proveedor'].queryset = Proveedores.objects.filter(categoria_pk=categoriaid).order_by('nombres_proveedor')	


	def clean_fecha_autorizacion(self):
		data = self.cleaned_data['fecha_autorizacion']
		#se verifica que la fecha de invitacion no este en el pasado
		utc = pytz.UTC
		now = utc.localize(datetime.today())
		#data = utc.localize(data)
		td = now - data
		logger.debug('data es '+ str(data))
		logger.debug('now es  '+ str(now))
		logger.debug('la resta es '+ str(td))
		if data.date() < now.date():
			logger.debug('entro al if de la fecha menor')
			raise ValidationError('Fecha no valida, ya que se encuentra en el pasado')
		#se retorna la data al caller	
		return data
	


class InvitacionForm(ModelForm):
	# guardar_invitado = forms.BooleanField(required=False)
	
	
	class Meta:
		model = Invitacion
		fields = ['fecha_invitacion','nombre_invitado','apellido_invitado','cedula_invitado','tipo_invitacion','save_contact','direccion_pk']
		labels = {
			'save_contact': 'Guardar Contacto',
		}
		help_texts = {
			'save_contact':'Da Clic si deseas que este Invitado se guarde en tu Libreta de Contactos.',
		}
	def __init__(self,user,*args,**kwargs):
		
		super(InvitacionForm,self).__init__(*args,**kwargs)
		self.fields['direccion_pk'].queryset = Direccion.objects.filter(residente_pk=user)


	def clean_fecha_invitacion(self):
		data = self.cleaned_data['fecha_invitacion']
		#se verifica que la fecha de invitacion no este en el pasado
		utc = pytz.UTC
		now = utc.localize(datetime.today())
		#data = utc.localize(data)
		td = now - data
		logger.debug('data es '+ str(data))
		logger.debug('now es  '+ str(now))
		logger.debug('la resta es '+ str(td))
		if data.date() < now.date():
			logger.debug('entro al if de la fecha menor')
			raise ValidationError('Fecha no valida, ya que se encuentra en el pasado')

		#se retorna la data al caller	
		return data

class InvitadoForm(ModelForm):
	class Meta:
		model = Invitado
		fields = ['nombres','apellidos','cedula','genero','email','telefono','movil']

	# def clean_dob(self):
	# 	data = self.cleaned_data['dob']
	# 	now = timezone.now()
	# 	if data > now:
	# 		logger.debug('fecha de nacimiento esta en el futuro')
	# 		raise ValidationError('Fecha de Nacimiento invalida, pues esta en el futuro')

	# 	return data

class DireccionForm(ModelForm):
	class Meta:
		model = Direccion
		fields = ['manzana','villa']
		labels = {
			'manzana':'Manzana',
			'villa':'Villa',
		}

egate/views.py
import pytz
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from . import models, forms
import datetime
import uuid
from django.utils import timezone
from datetime import timedelta
import logging

logger = logging.getLogger(__name__)

# Create your views here.
def index(request):
   # return HttpResponse("Hello, world. You're at the egate index.")

   return render(request,'egate/index.html')

@login_required(login_url='login')
def main(request):
	return render(request,'egate/main.html')

@login_required(login_url='login')
def todayInvitations(request):
	today_list = models.Invitacion.objects.filter(fecha_invitacion__date=datetime.date.today(), residente_pk=request.user)
	today_list_provider = models.AutorizarProveedor.objects.filter(fecha_autorizacion__date=datetime.date.today(),residente_pk=request.user)
	#today_list = models.Invitacion.objects.all()
	context = {'invitation_list': today_list, 'autorizacion_list':today_list_provider}
	return render(request,'egate/view_invitations.html',context)

@login_required(login_url='login')
def nextInvitations(request,timeslot):

	if timeslot == "thisweek":
		d = 7
	days_forward = datetime.date.today() + timedelta(days=d)
	start_date = datetime.date.today()
	if d == 7:
		week_list = models.Invitacion.objects.filter(residente_pk=request.user).exclude(fecha_invitacion__lt=datetime.date.today()).filter(fecha_invitacion__range=(start_date,days_forward))
		week_list_provider = models.AutorizarProveedor.objects.filter(residente_pk=request.user).exclude(fecha_autorizacion__lt=datetime.date.today()).filter(fecha_autorizacion__range=(start_date,days_forward))
	context = {'invitation_list':week_list, 'autorizacion_list':week_list_provider}
	return render(request,'egate/view_invitations.html',context)

@login_required(login_url='login')
def previousInvitations(request,timeslot):
	d=0
	
	if timeslot == "lastweek":
		d= 7
	if timeslot == "lastmonth":
		d= 30
	if timeslot == "all":
		d= 0
	
	days_ago = datetime.date.today() - timedelta(days=d)
	start_date = datetime.date.today()

	if d == 0:
		week_list = models.Invitacion.objects.filter(residente_pk=request.user)	
		week_list_provider = models.AutorizarProveedor.objects.filter(residente_pk=request.user)	

	else:
		week_list = models.Invitacion.objects.filter(residente_pk=request.user).exclude(fecha_invitacion__gt=datetime.date.today()).filter(fecha_invitacion__range=(days_ago,start_date))
		week_list_provider = models.AutorizarProveedor.objects.filter(residente_pk=request.user).exclude(fecha_autorizacion__gt=datetime.date.today()).filter(fecha_autorizacion__range=(days_ago,start_date))
	context = {'invitation_list':week_list, 'autorizacion_list':week_list_provider}
	return render(request,'egate/view_invitations.html',context)

@login_required(login_url='login')
def crearAutorizacionProveedor(request):
	if request.method == "POST":
		form = forms.AutorizaProveedorForm(request.user,data=request.POST)
		if form.is_valid():
			prev_form = form.save(commit=False)
			now = timezone.now()
			prev_form.fecha_emision = now
			prev_form.estado_autorizacion = 'P'
			myId = uuid.uuid1()
			prev_form.codigo_invitacion = myId.hex
			prev_form.residente_pk = request.user
			prev_form.save()
			return redirect('todayinvitations')

	else:
		#se valida que antes de generar una invitacion el cliente tenga dato de su direccion
		try:
			tieneDireccion = models.Direccion.objects.filter(residente_pk=request.user.id)
		except models.Direccion.DoesNotExist:
			tieneDireccion = None
		if not tieneDireccion:
			return redirect('creardireccion')
		direcciondata = tieneDireccion
		direccionpk = direcciondata[0].id
		logger.debug('el id de direccion es ' + str(direcciondata[0].id))

		form = forms.AutorizaProveedorForm(request.user)
	return render(request,'egate/autorizaproveedorform.html',{'form':form})	

#view para obtener solamente los proveedores que la categoria seleccionada entreguen
def cargarProveedores(request):
	categoria_id = request.GET.get('nombres_categoria')
	proveedores = models.Proveedores.objects.filter(categoria_pk = categoria_id).order_by('nombres_proveedor')
	return render(request,'egate/dropdownproveedores.html',{'proveedores':proveedores})

@login_required(login_url='login')
def crearInvitacion(request):
	if request.method =="POST":	
		form = forms.InvitacionForm(request.user,data=request.POST)
		if form.is_valid():
			prev_form = form.save(commit=False)
			# now = datetime.datetime.now(tz=timezone.utc)
			now = timezone.now()
			prev_form.fecha_emision = now
			prev_form.estado_invitacion = 'P'
			myId = uuid.uuid1()
			prev_form.codigo_invitacion = myId.hex
			prev_form.residente_pk = request.user
			prev_form.save()
			#si se marco el visto de grabar se guarda un contacto
			if prev_form.save_contact:
				myform = request.POST.copy()
				models.Invitado.objects.create(
					nombres = myform.get('nombre_invitado'),
					apellidos = myform.get('apellido_invitado'),
					cedula = myform.get('cedula_invitado'),
					pk_user = request.user
					)
			return redirect('todayinvitations')
		else:
			messages.error(request,"Por favor revise las observaciones indicadas abajo")
	else:
		#se valida que antes de generar una invitacion el cliente tenga dato de su direccion
		try:
			tieneDireccion = models.Direccion.objects.filter(residente_pk=request.user.id)
		except models.Direccion.DoesNotExist:
			tieneDireccion = None
		if not tieneDireccion:
			return redirect('creardireccion')
		#fdv
		direcciondata = tieneDireccion
		direccionpk = direcciondata[0].id
		logger.debug('el id de direccion es ' + str(direcciondata[0].id))
		
		form = forms.InvitacionForm(request.user)

	return render(request,'egate/invitacionform.html',{'form':form})

@login_required(login_url='login')
def crearDireccion(request):
	if request.method == "POST":
		form = forms.DireccionForm(request.POST, request.user)
		if form.is_valid():
			prev_form = form.save(commit=False)
			prev_form.residente_pk = request.user
			prev_form.save()
			return redirect('main')
	else:
		form = forms.DireccionForm(instance=request.user)
	return render(request,'egate/direccionform.html',{'form':form})

@login_required(login_url='login')
def crearInvitado(request):
	if request.method == "POST":
		form = forms.InvitadoForm(request.POST, request.user)
		if form.is_valid():
			prev_form = form.save(commit=False)
			prev_form.pk_user = request.user
			prev_form.save()
			return redirect('main')
		else:
			messages.error(request,"Por favor revise las observaciones indicadas abajo")
	else:
		form = forms.InvitadoForm(instance=request.user)

	return render(request, 'egate/invitadoform.html',{'form':form})

@login_required(login_url='login')
def setInvitationState(request,mypk):
	if request.method == "GET":
		invitation_element = models.Invitacion.objects.get(pk=mypk)
		invitation_element.estado_invitacion = 'C'
		invitation_element.save()
	return redirect('todayinvitations')

egate/templates/egate/autorizaproveedorform.html
{% extends 'egate/layout.html' %}
{% load widget_tweaks %}
{% load materializecss %}
{% block content %}
<div>
  <h2>Autorizar Ingreso de Proveedores</h2>
</div>

<div>
<form method="post" id="autorizaproveedorform" data-proveedor-url="{% url 'ajax_cargarproveedores' %}" novalidate>
	{% csrf_token %}
  {{ form.non_field_errors }}
  <div class="fieldWrapper">
  	
  	{{form.fecha_autorizacion.errors }}
  	<label for="{{ form.fecha_autorizacion.id_for_label }}">Fecha de Autorizacion</label>
  	
  		{{form.fecha_autorizacion | add_class:"datepicker"}} 		
 
  </div>

    <div class="fieldWrapper">
    {{form.nombres_categoria.errors}}
    <label for="{{ form.nombres_categoria.id_for_label }}">Categoria</label>
    {{form.nombres_categoria}}
  </div>

  <div class="fieldWrapper">
  	{{form.nombre_proveedor.errors}}
  	<label for="{{ form.nombre_proveedor.id_for_label }}">Proveedor</label>
    <div class="input-field"> 
  	{{form.nombre_proveedor | add_class:"browser-default"}}
    </div>
  </div>  
 
<div class="fieldWrapper">      
      {{form.direccion_pk.errors}}
      <label for="{{ form.direccion_pk.id_for_label }}">Direccion de Domicilio</label>
      <div class="input-field">     
      {{form.direccion_pk}}
      </div>      
  </div>

 
  <div class="fieldWrapper"> 
  	<button type="submit">Autorizar</button>
  </div>
</form>
</div>

{% endblock %}

egate/templates/egate/direccionform.html
{% extends 'egate/layout.html' %}
{% load widget_tweaks %}
{% load materializecss %}

{% block content %}
<div>
  <h2>Mi Direccion</h2>
</div>
<div>
  <p>
    Por favor ingrese su direcci&oacute;n o su ubicaci&oacute;n residencial
  </p>
</div>
<div>
	<form method="post">
		{% csrf_token %}
		{{ form.non_field_errors }}
		<div class="fieldWrapper">
			{{form.manzana.errors }}
  			<label for="{{ form.manzana.id_for_label }}">Manzana</label>  		
  			{{form.manzana }}
		</div>
		<div class="fieldWrapper">
			{{form.villa.errors }}
  			<label for="{{ form.villa.id_for_label }}">Villa</label>  		
  			{{form.villa }}
		</div>
		<div class="fieldWrapper"> 
  		<button type="submit">Agregar</button>
  		</div>
	</form>
</div>
{% endblock %}

egate/templates/egate/dropdownproveedores.html
<option value="">---------</option>
{% for prov in proveedores %}
<option value="{{ prov.pk }}">{{ prov.nombres_proveedor }}</option>
{% endfor %}

egate/templates/egate/index.html
{%extends 'egate/layout.html' %}

{% block content %}
<div>
  <a style="display: block;" class="center-align" href="{% url 'login' %}">Login User</a>
</div>
{% endblock %}

egate/templates/egate/invitacionform.html
{% extends 'egate/layout.html' %}
{% load widget_tweaks %}
{% load materializecss %}
{% block content %}
<div>
  <h2>Invitacion</h2>
</div>

<div>
<form method="post">
	{% csrf_token %}
  {{ form.non_field_errors }}
  <div class="fieldWrapper">
  	
  	{{form.fecha_invitacion.errors }}
  	<label for="{{ form.fecha_invitacion.id_for_label }}">Fecha de Invitacion</label>
  		
  		{{form.fecha_invitacion | add_class:"datepicker"}} 		
 
  </div>
  <div class="fieldWrapper">
  	{{form.nombre_invitado.errors}}
  	<label for="{{ form.nombre_invitado.id_for_label }}">Nombres</label>
  	{{form.nombre_invitado}}
  </div>
    <div class="fieldWrapper">
  	{{form.apellido_invitado.errors}}
  	<label for="{{ form.apellido_invitado.id_for_label }}">Apellidos</label>
  	{{form.apellido_invitado}}  
  </div>
  <div class="fieldWrapper">
  	{{form.cedula_invitado.errors}}
  	<label for="{{ form.cedula_invitado.id_for_label }}">Documento de Identidad</label>
  	{{form.cedula_invitado}}
  </div>
  
  <div class="fieldWrapper">    	
  		{{form.tipo_invitacion.errors}}
  		<label for="{{ form.tipo_invitacion.id_for_label }}">La visita tiene caracter..</label>
  		<div class="input-field">  		
  		{{form.tipo_invitacion}}
  		</div>  		
  </div> 
<div class="fieldWrapper">      
      {{form.direccion_pk.errors}}
      <label for="{{ form.direccion_pk.id_for_label }}">Direccion del Residente</label>
      <div class="input-field">     
      {{form.direccion_pk}}
      </div>      
  </div>
  <div class="fieldWrapper">
    {{form.save_contact.errors}}
    
    <div>
      <label for="{{ form.save_contact.id_for_label }}"></label>  
      {{form.save_contact | materializecss}}          
    </div>

  </div>
 
  <div class="fieldWrapper"> 
  	<button type="submit">Invitar</button>
  </div>
</form>
</div>

{% endblock %}

egate/templates/egate/invitadoform.html
{% extends 'egate/layout.html' %}
{% load widget_tweaks %}
{% load materializecss %}
{% block content %}
<div>
  <h2>Grabar un Invitado</h2>
</div>
<div>
<form method="post">
	{% csrf_token %}
  {{ form.non_field_errors }}
  
  <div class="fieldWrapper">
    {{form.nombres.errors}}
    <label for="{{ form.nombres.id_for_label }}">Nombres</label>
    {{ form.nombres }}
  </div>

  <div class="fieldWrapper">
    {{ form.apellidos.errors }}
    <label for="{{ form.apellidos.id_for_label }}">Apellidosss</label>
    {{ form.apellidos }}
  </div>
  
  <div class="fieldWrapper">
    {{ form.cedula.errors}}
    <label for="{{ form.cedula.id_for_label }}">Cedula</label>
    {{ form.cedula }}
  </div>
  <div class="fieldWrapper">
    {{form.genero.errors}}
    <label for="{{ form.genero.id_for_label }}">Sexo</label>
    {{ form.genero }}
  </div>
  <div class="fieldWrapper">
    {{ form.email.errors }}
    <label for="{{ form.email.id_for_label }}">Email</label>
    {{ form.email }}
  </div>
  <div class="fieldWrapper">
    {{ form.telefono.errors }}
    <label for="{{ form.telefono.id_for_label }}">Telefono</label>
    {{ form.telefono }}
  </div>
  <div class="fieldWrapper">
    {{ form.movil.errors}}
    <label for="{{ form.movil.id_for_label }}">Movil</label>
    {{ form.movil }}
  </div>
  <input type="submit"/>
</form>
</div>

{% endblock %}

egate/templates/egate/layout.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Egate App</title>
  <link href="http://joinpoint.org/saebl/favicon_yinyang.ico" rel="icon" type="image/x-icon">
  
  {% block css %}
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.1/css/materialize.min.css" integrity="sha256-qj3p6P1fJIV+Ndv7RW1ovZI2UhOuboj9GcODzcNFIN8=" crossorigin="anonymous" />
  {% endblock css %}
  
  <!-- [if IE]>
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
  <![endif] -->
  
</head>
<body>
<header>
  <!-- Dropdown Structure -->
  <ul id="dropdown1" class="dropdown-content">
          <li><a href="{% url 'change_password' %}">Cambiar Password</a></li>
          <li class="divider"></li>
          <li><a href="{% url 'logout' %}">Logout User</a></li>
  </ul>  
  <nav>
    <div class="nav-wrapper">
      <a href="{% url 'main' %}" class="brand-logo center">EGate APP</a>
      <ul id="nav-mobile" class="left hide-on-med-and-down">
        {% if user.is_authenticated %}
        <li class="active"><a href="{% url 'main' %}">Home</a></li>
        <li><a href="{% url 'invitacion' %}">Autorizar Invitados</a></li> 
        <li><a href="{% url 'autorizarproveedor' %}">Autorizar Proveedor</a></li>   
        <!-- Dropdown Trigger -->
        <li><a class="dropdown-trigger" href="#!" data-target="dropdown1" >Mi Cuenta<i class="material-icons left">arrow_drop_down</i></a></li>    
        {% endif %}     
      </ul>
    </div>
  </nav>     
  
</header>  
  <div class="container">
    {% block content %}
    {% endblock %}
    <br>
  </div>
  <footer></footer>
{% block javascript %}
<script
src="https://code.jquery.com/jquery-3.3.1.min.js"
integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
crossorigin="anonymous"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.1/js/materialize.min.js" integrity="sha256-SrBfGi+Zp2LhAvy9M1bWOCXztRU9Ztztxmu5BcYPcPE=" crossorigin="anonymous"></script>
<script>
$(document).ready(function(){

// Initialize materialize data picker
$('.datepicker').datepicker({format: 'yyyy-mm-dd',autoClose:true,changeMonth:true,changeYear:false});
$('.datepicker-i').datepicker({format: 'yyyy-mm-dd',autoClose:true,changeMonth:true,changeYear:true,minDate:new Date(1950,0,1),maxDate:new Date(),defaultDate: new Date(1950,0,1),yearRange:70,});
$('select').formSelect();

$(".dropdown-trigger").dropdown();

  $("#id_nombres_categoria").change(function(){

    var url = $('#autorizaproveedorform').attr("data-proveedor-url");
    var categoria_id = $(this).val();

    $.ajax({

      url: url,
      data:{'nombres_categoria':categoria_id},
      success: function(data){
        $("#id_nombre_proveedor").html(data);
      },
    });

  });

});
</script>
{% endblock javascript %}
</body>
</html>

egate/templates/egate/main.html
{%extends 'egate/layout.html' %}

{% block content %}


<div>
	<a href="{% url 'todayinvitations' %}">Invitaciones del Dia</a>
</div>

<div>
	<a href="{% url 'timeslotnextinvitations' 'thisweek' %}">Invitaciones de esta Semana</a>
</div>

<div>
	<a href="{% url 'timeslotinvitations' 'lastweek' %}">Invitaciones Hace 7 dias</a>
</div>
<div>
	<a href="{% url 'timeslotinvitations' 'lastmonth' %}">Invitaciones del Mes</a>
</div>
<div>
	<a href="{% url 'timeslotinvitations' 'all' %}">Todas mis invitaciones</a>
</div>

<div>
	<a href="{% url 'crearinvitado' %}">Grabar Invitado</a>
</div>




{% endblock %}